name = "milagre-relay"
main = "src/worker.ts"
compatibility_date = "2026-09-01"
routes = [{ pattern = "relay.milagre.cloud", custom_domain = true }]

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]
